apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-cache-pvc
  namespace: f1-predictor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-logs-pvc
  namespace: f1-predictor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi